// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXb_8IuxrdeZNL7s6p9oWVfOmE64nEM_M',
    appId: '1:43434605661:web:f8ce567aa50243061a21b4',
    messagingSenderId: '43434605661',
    projectId: 'pr-8-firebase-miner',
    authDomain: 'pr-8-firebase-miner.firebaseapp.com',
    storageBucket: 'pr-8-firebase-miner.appspot.com',
    measurementId: 'G-DD5E6F35X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9oyrKXKBuf3sM7Aj8qj-34KhGzKCHn0A',
    appId: '1:43434605661:android:1a470b78a33348db1a21b4',
    messagingSenderId: '43434605661',
    projectId: 'pr-8-firebase-miner',
    storageBucket: 'pr-8-firebase-miner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMkRKj0qbwCEBrWaHf2dxVQOPpPA0BYNc',
    appId: '1:43434605661:ios:fa517856322d76d01a21b4',
    messagingSenderId: '43434605661',
    projectId: 'pr-8-firebase-miner',
    storageBucket: 'pr-8-firebase-miner.appspot.com',
    iosBundleId: 'com.example.pr8ChattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMkRKj0qbwCEBrWaHf2dxVQOPpPA0BYNc',
    appId: '1:43434605661:ios:fa517856322d76d01a21b4',
    messagingSenderId: '43434605661',
    projectId: 'pr-8-firebase-miner',
    storageBucket: 'pr-8-firebase-miner.appspot.com',
    iosBundleId: 'com.example.pr8ChattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXb_8IuxrdeZNL7s6p9oWVfOmE64nEM_M',
    appId: '1:43434605661:web:953e0c77cc7ae3ce1a21b4',
    messagingSenderId: '43434605661',
    projectId: 'pr-8-firebase-miner',
    authDomain: 'pr-8-firebase-miner.firebaseapp.com',
    storageBucket: 'pr-8-firebase-miner.appspot.com',
    measurementId: 'G-NZ8GVVT9PK',
  );
}
